dist: bionic

jobs:
  include:
  - name: pongo shell
    env: TEST_SCRIPT="assets/ci/pongo_shell.test.sh"
  - name: pongo build, pongo expose
    env: TEST_SCRIPT="assets/ci/pongo_build.test.sh assets/ci/pongo_expose.test.sh"
  - name: pongo run (CE releases)
    env: TEST_SCRIPT="assets/ci/pongo_run_ce.test.sh"
  - name: pongo run (EE releases)
    env: TEST_SCRIPT="assets/ci/pongo_run_ee.test.sh"

env:
  global:
  # for Enterprise images
  - PULP_USERNAME=admin
  - secure: rRp9T8GGVfmA+DjVXZQNWrtIysZL47sMlkHyARDgW7v01FYfkDN0wj5m9dFdufrjQv2kq9rKsAlaN2cZEKN2EGnvF+6R3qZ9LI4MjBqD3w7wqy90jgzO85KUPNATLoAi8u0zdurKKFokoeKthxiPNDtSe4HwqsIWcboeJogZearIMHJiT7OYKgrjmyfy4hKP2UdXRCsnFmor5FCLqlycSVLGx4go0d75lKnzeRqinFBQOmI7pg/852HOE9fPDqQuU9aXIpjUokZxAW+JnZzC9YR8gFCe1/0x9JCKU3zAGJpHcyzD7D/GTmGfAAYxrltRExeCglh2BSOUXNoafWrpYBnk9IP2UF7PWFNbBC/bJ+PQkOnNAsxT9MR8cIR1RpDhHVolTEIT8syOLOy+3Kz7AISBbATbucEqVvBFgc/01RU0yWg5eZ2XJEMdH6+NGxm3WKME8EYcUfZc0T7pWGuOw23BZOc7nmXljrq0pTjkG5ad1X7PPhk3NBt2z+0HWUtAqv31Mrdt0ZZhwWLOT7j3smC7wz/vLaJF/7/T9JwbFvWcyntlp7NfLR2vK6TW1hD6Gz5wLMetzriRIZq2iOFPdx+9zIUx4LIZwzJbBYmW102I1n5j7KzfEH/+3llKeLuLHM88E/tLralZIeOsQiEbdX791IDciJNkaboeNqQKBWc=
  # for Nightly and Enterprise images
  - DOCKER_USERNAME=kongcloudpull
  - secure: JFCQIhYT4iXwwl3J9HSSywwJZhl9lj/b837KXqSGIn8LYxOAMm5baja9f0I966cATcMhzg+M+jJRXz4DrpDcbCvSrtXx0mNtaPU7Vc7HcnaW1/VVcLQ+AbU+GO7TPoItLTX257TkcAv0E7I7E4z/QSRRT0xTU8PDxaBt1MqTCk/wYTExaOTddvfMUWCZQdEVZoTccgip90zBv157EST/pT8re28auaG/cTRWAjly1RL42aKIYjXs6tT+iAA7c4mgKb5Q+0TRoH5wjbXeBe6FfyPY7dtQqIGsHSZJ6ANuEkVKAnmjdnsaRVTgmqhptnebjtX3/Xr10RgsRcEqZMNoi4dEAKytDAWJpdsJlz6X7cruTU3kt2DjzUlA7SCm6HozPTEtjjMZ1rlVrTgKoxhqUtymHodkmSOBUKIBBYeno/VBvYlcWzQOW/ylfd+2r9FNtz+E0joMQRz/8aT8/DmaPg6Orzqbt1qvyS7kZo9aoakv+cW2l1OIK44pLwCnhQMj/W1//lefxCKi6iVdc/UfqVWSq9RBhqG7eaLwLaddEAKUvgf4GCw7SrzpLoBiu8bd+ffC+7jxKAVK8LC7XDkFzNrcD+DeIDolCSRWPXcRfcaJ22yw6tCWocXh3z1CC08YQNy7sdbrOnzjUKAlGAxH2dcHJeSDq7SBiOrFWv7atJw=

install:
- sudo apt-get install figlet
- make install
- export PATH=~/.local/bin/:$PATH

script:
- make lint
- assets/ci/run.sh --suite "Pongo test suite" $TEST_SCRIPT
