dist: bionic
jobs:
  include:
  - name: pongo shell
    env: TEST_SCRIPT="assets/ci/pongo_shell.test.sh"
  - name: pongo build, pongo expose
    env: TEST_SCRIPT="assets/ci/pongo_build.test.sh assets/ci/pongo_expose.test.sh"
  - name: pongo run (CE releases)
    env: TEST_SCRIPT="assets/ci/pongo_run_ce.test.sh"
  - name: pongo run (EE releases)
    env: TEST_SCRIPT="assets/ci/pongo_run_ee.test.sh"
env:
  global:
  # for Enterprise images
  - PULP_USERNAME=admin
  - secure: cWRtevuFdESmsaWQ+NMY3z2gCpuuFrjvUiF7JU2qgJnPQhVt4o+VLyXi9RzZx5V6EMPScGtzwQH12rarABTbnd2ZKHgyFk+6r5WrbtRIbdsfBdd0QJaEqYTNYTMO4LVc6wy4/brcyOthHZCL5V/Gl8gAnhg/H9fEFeWi6XPUAEw4rONf0bRkPlOQiLYaEX7Uso6tS8AO9fAgYeS12RFgSaCC38BWiYcghts3ekjpchU07G09U2u1cmYn6kVcKjsCtjuTgDCZUdYLnURaxRZd0OWZrTu/F5xMS2Kef/cVpcCi9/pWZox+vOK6/RHyh5o85v0920BPtBVYp46jFa45O6cnnpe67UHTZQ0ripNm7BxaAvnwVtfvY/s54+KAN2R3dC03J2/CE9qaGe8f31B9TeLrcSIHu3ju8b4qquhS8dT5yj4Rf+38h48BVTweDri4iDt8iqPEzaCti+MPDOg2jXMBHDKckj0mK3VzKBAmdEjm/LxrWcs12CkhV6pM5tJS6+6STULaH7zAbCtJdjO0fBs9xHHe54B04phw/SUOFSBRgY9XD5Inm1Ibou6LMrmMSWztWVrIInB7urGKdH+CohEN83f1QQCQb8SNKi/iU1zevhvYTthB6IdLOX+rKT1HtN+rSe1Oy0Dc1YB0eyW0nG9z/nYIqSFzUVFLwN0UjAY=
  - DOCKER_USERNAME=kongcloudpull
  - secure: BuFWr8e3qAsDg6pGLkfTWymmrbES8Kw/TEjK8KpE6GKPWLpxnGabSGG23eyDCaHCLQVoWDWQprdk6Zf8amkMrDwNwKYk6Q7drteOxRQP4x7PLy3t469Cbwg2oI3+iJruIKUYHKBMBz4PMu7t/79CdPpZZKf1xuNUexdYJfnRGzCQ2juFvgQSxM/kFrniS2/30NvD5JZ9Rwj+JtaxI2V0cSWBE30p4IQ8w0MC5sdV/zoRROKlLnm3oUOfUWGh7r8gtncOrzf20wq3jnB36EOU8NmCZnTBfUnJhsrGuCANvYWQt+REYg0DNmF1jOpErBtKWMdVSRnvpi5YvcY4jOZzooFnObDtNkIDO0WfgRlmNZPFkKRKUAFGSkFDbTrMAb+YFDQtyST2H5eP+aTt1q5Py4w/tRXSTVDj4fYmbGxD+Zk3MViCIj1uhCQoDHXH0eoHlunHcVcidUI5862TQes4LqA9qep59gh8knWQ26HdgWszaDtHhqVyI/V1nM/w+5oaM8fmUrD+3zGqOAmaMNRUf9wfofW/piiPK0iW7R75PoS9QJJeI5AiQc902m+t5VNUVPqUi81WkTEuPhL9lz9FjN54bis4/Nc7DQLyPqW/2Jow1DN4pMhlASr6XT0uP7BfnXUFwAki6wF4J69YUzbwhSsyy/u8u8pyZ8GIqFilX30=
install:
- sudo apt-get install figlet
- make install
- export PATH=~/.local/bin/:$PATH
script:
- make lint
- assets/ci/run.sh --suite "Pongo test suite" $TEST_SCRIPT
